config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations] 
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
    end
  resources :apartments
  resources :tenants
  resources :leases do
    put 'new_rent', as: 'new_rent', on: :member
  end
  
  root "apartments#index"

end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
    has_many :leases
    has_many :tenants, through: :leases
    def unit_name
        "#{building} ##{unit}"
    end

end

app/models/lease.rb
class Lease < ActiveRecord::Base
    belongs_to :apartment, required: true
    belongs_to :tenant, required: true
    
    def rent_owed
        now = Time.now.utc.to_date
        if self.start_date != nil
            months_into_lease = now.month - self.start_date.month - (self.start_date.to_date.change(:month => now.month) > now ? 1 : 0) + 1
            (months_into_lease * monthly_rent) - paid_rent
        end
    end

end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
    has_many :leases
    has_many :tenants, through: :leases
    validates :first_name, :last_name, :dob, presence: true
    def full_name
        "#{last_name}, #{first_name}"
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :registerable, 
         :rememberable, :trackable, :validatable
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @apartments = Apartment.all
  end

  def show
  end

  def new
    @apartment = Apartment.new
  end

  def edit
  end

  def create
  end

  def update
    if @apartment.update(apartment_params)
      redirect_to @apartment, notice: 'Apartment was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
  end

  private

    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    def apartment_params
      params.require(:apartment).permit(:building, :unit, :paint_scheme, 
                                        :kitchen_counter, :bathroom_sink, 
                                        :refrigerator_type, :ac_filter, 
                                        :ac_maint, :refrigerator_maint, :notes)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/leases_controller.rb
class LeasesController < ApplicationController
  before_action :set_lease, only: [:show, :edit, :update, :destroy, :new_rent]
  before_action :authenticate_user!
    
  def index
    @leases = Lease.all
  end

  def show
  end

  def new
    @lease = Lease.new
  end
  
  def edit
  end
  
  def create
    @lease = Lease.new(lease_params)
  
    if @lease.save 
        redirect_to root_path, notice: "Successfully created new Lease for #{@lease.apartment.unit_name}"
    else
        render 'new'
    end
  end
  
  def update
    if @lease.update(lease_params)
      redirect_to root_path, notice: 'Lease was successfully updated.'
    else
      render 'edit'
    end
  end
  
  def destroy
    @lease.destroy
    redirect_to root_path
  end
  
  def new_rent
    @lease.paid_rent += params[:new_rent].to_i
    @lease.save
    if @lease.rent_owed == 0
      flash[:alert] = "Tenant is up to date!"
    elsif @lease.rent_owed > 0
      flash[:notice] = "Tenant still owes $#{@lease.rent_owed}"
    elsif @lease.rent_owed < 0
      flash[:notice] = "Tenant has a credit of $#{@lease.rent_owed.abs}!"
    end
    redirect_to @lease.apartment
  end
  
  private

    def set_lease
      @lease = Lease.find(params[:id])
    end

    def lease_params
      params.require(:lease).permit(:start_date, :end_date, :full_lease, :notes, :tenant_id, :apartment_id, :monthly_rent, :paid_rent)
    end
    
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  before_action :set_tenant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
    
  def index
    @tenants = Tenant.all
  end

  def show
  end

  def new
    @tenant = Tenant.new
  end
  
  def edit
  end
  
  def create
    @tenant = Tenant.new(tenant_params)
    
    if @tenant.save 
        redirect_to @tenant, notice: "Successfully created new Tenant"
    else
        render 'new'
    end
  end
  
  def update
    if @tenant.update(tenant_params)
      redirect_to @tenant, notice: 'Tenant was successfully updated.'
    else
      render 'edit'
    end
  end
  
  def destroy
  end
  
  private

    def set_tenant
      @tenant = Tenant.find(params[:id])
    end

    def tenant_params
      params.require(:tenant).permit(:first_name, :last_name, :dob, :notes)
    end
    
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def find_age(birthday)
    now = Time.now.utc.to_date
    now.year - birthday.year - (birthday.to_date.change(:year => now.year) > now ? 1 : 0)
  end
    
end

app/helpers/leases_helper.rb
module LeasesHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/views/apartments/_form.html.erb
<%= form_for @apartment do |f| %>
    <div class="input-group input-group-md">
        <%= f.label :paint_scheme, class: "input-group-addon chriswidth" %>
        <%= f.text_field :paint_scheme, class: "form-control" %>
    </div>
    <br />
    <div class="input-group input-group-md">
        <%= f.label :kitchen_counter, class: "input-group-addon chriswidth" %>
        <%= f.text_field :kitchen_counter, class: "form-control" %>
    </div>
    <br />
    <div class="input-group input-group-md">
        <%= f.label :bathroom_sink, class: "input-group-addon chriswidth" %>
        <%= f.text_field :bathroom_sink, class: "form-control" %>
    </div>
    <br />
    <div class="input-group input-group-md">
        <%= f.label :refrigerator_type, class: "input-group-addon chriswidth" %>
        <%= f.text_field :refrigerator_type, class: "form-control" %>
    </div>
    <br />
    <div class="input-group input-group-md">
        <%= f.label :ac_filter, class: "input-group-addon chriswidth" %>
        <%= f.text_field :ac_filter, class: "form-control" %>
    </div>
    <br />
    <div class="input-group input-group-md">
        <%= f.label :ac_maint, class: "input-group-addon chriswidth" %>
        <%= f.text_field :ac_maint, class: "datepicker form-control" %>
        <script type="text/javascript">
            $(document).ready(function(){
                $('.datepicker').datepicker({
                    format: 'yyyy-mm-dd'
                });
            });
        </script>
    </div>
    <br />
    <div class="input-group input-group-md">
        <%= f.label :refrigerator_maint, class: "input-group-addon chriswidth" %>
        <%= f.text_field :refrigerator_maint, class: "datepicker form-control" %>
        <script type="text/javascript">
            $(document).ready(function(){
                $('.datepicker').datepicker({
                    format: 'yyyy-mm-dd'
                });
            });
        </script>
    </div>
    <br />
    <%= f.label :notes %>
    <br />
    <%= f.text_area :notes, class: "form-control", rows: "5" %>
    <br />
    <div class="text-center"><%= f.submit "Submit", class: "btn btn-danger" %></div>
<% end %>

app/views/apartments/edit.html.erb
<h1 class="text-center">Edit <%= @apartment.building %> #<%= @apartment.unit %> Details:</h1>

<%= render 'form' %>

app/views/apartments/index.html.erb
<h2 class="text-center">Apartment List</h2>
<div class="row">
    <% @apartments.each_slice(4) do |building| %>
        <div class="col-lg-3 col-md-3 col-sm-4 col-xs-6">
            <div class="jumbotron">
            <% building.each do |apt| %>
                <div class="text-center">
                    <% color_code = "" %>
                    <% if apt.leases.first == nil %>
                        <% color_code = "danger" %>
                    <% elsif apt.leases.first.rent_owed > 0 %>
                        <% color_code = "warning" %>
                    <% else %>
                        <% color_code = "success" %>
                    <% end %>
                    <h1><%= link_to "#{apt.building} ##{apt.unit}", apartment_path(apt), class: "btn btn-#{color_code} btn-lg", style: "font-weight: 900; border-width: 10px; border-radius: 30px;" %></h1>
                </div>
            <% end %>
            </div>
        </div>
    <% end %>
</div>

app/views/apartments/show.html.erb
<div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
        <h1 class="text-center"><%= @apartment.building %> #<%= @apartment.unit %> Details:</h1>
        <div class="well">
            <p class="input-group input-group-md">
                <span class="input-group-addon chriswidth">Paint Scheme:</span> 
                <span class="form-control"><%= @apartment.paint_scheme %></span>
            </p>
            <p class="input-group input-group-md">
                <span class="input-group-addon chriswidth">Kitchen Counter Type:</span> 
                <span class="form-control"><%= @apartment.kitchen_counter %></span>
            </p>
            <p class="input-group input-group-md">
                <span class="input-group-addon chriswidth">Bathroom Amenities:</span> 
                <span class="form-control"><%= @apartment.bathroom_sink %></span>
            </p>
            <p class="input-group input-group-md">
                <span class="input-group-addon chriswidth">Refrigerator Type:</span> 
                <span class="form-control"><%= @apartment.refrigerator_type %></span>
            </p>
            <p class="input-group input-group-md">
                <span class="input-group-addon chriswidth">AC Filter Type:</span> 
                <span class="form-control"><%= @apartment.ac_filter %></span>
            </p>
            <p class="input-group input-group-md">
                <span class="input-group-addon chriswidth">AC Filter Last Changed:</span> 
                <span class="form-control">
                    <%= @apartment.ac_maint ? "#{time_ago_in_words(@apartment.ac_maint)} ago." : nil %>
                </span>
            </p>
            <p class="input-group input-group-md">
                <span class="input-group-addon chriswidth">Refrigerator Last Maintained:</span> 
                <span class="form-control">
                    <%= @apartment.ac_maint ? "#{time_ago_in_words(@apartment.refrigerator_maint)} ago" : nil %>
                </span>
            </p>
            <p class="input-group input-group-md">
                <span class="input-group-addon chriswidth">Last Update:</span> 
                <span class="form-control"><%= @apartment.updated_at %></span>
            </p>
            <p class="input-group input-group-md">
                <span class="input-group-addon chriswidth">Notes:</span>
                <span class="form-control"><%= @apartment.notes %></span>
            </p>
            <br />
            <p class="text-center">
                <%= link_to "Edit", edit_apartment_path(@apartment), class: "btn btn-warning" %> 
                <%= link_to "Home", root_path, class: "btn btn-info" %>
            </p>
        </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
        <h1 class="text-center">Tenant Details:</h1>
        <div class="well">
            <p class="input-group input-group-md">
                <span class="input-group-addon chriswidth">Current Tenant:</span>
                <span class="form-control">
                    <% if @apartment.tenants.first %>
                        <%= @apartment.tenants.first.first_name %> <%= @apartment.tenants.first.last_name %>
                    <% else %>
                        <span class="text-danger">Vacant</span>
                    <% end %>
                </span>
            </p>
            <p class="input-group input-group-md">
                <span class="input-group-addon chriswidth">Date of Birth:</span> 
                <span class="form-control">
                    <% if @apartment.tenants.first != nil %>
                        <%= @apartment.tenants.first.dob %>
                    <% end %>
                </span>
            </p>
            <p class="input-group input-group-md">
                <span class="input-group-addon chriswidth">Rent Owed:</span> 
                <span class="form-control">
                    <% if @apartment.leases.first != nil %>
                        <%= "$#{ @apartment.leases.first.rent_owed}" %>
                    <% end %>
                </span>
            </p>
            <p class="input-group input-group-md">
                <span class="input-group-addon chriswidth">Age:</span> 
                <span class="form-control">
                    <% if @apartment.tenants.first != nil %>
                        <%= "#{ find_age @apartment.tenants.first.dob} years old" %>
                    <% end %>
                </span>
            </p>
            <p class="input-group input-group-md">
                <span class="input-group-addon chriswidth">Last Update:</span> 
                <span class="form-control">
                    <% if @apartment.tenants.count != 0 %>
                        <%= @apartment.tenants.first.updated_at %>
                    <% end %>
                </span>
            </p>
            <p class="input-group input-group-md">
                <span class="input-group-addon chriswidth">Notes:</span>
                <span class="form-control">
                    <% if @apartment.tenants.count != 0 %>
                        <%= @apartment.tenants.first.notes %>
                    <% end %>
                </span>
            </p>
            <br />
            <p class="text-center">
                <% if @apartment.leases.count != 0 %>
                    <%= link_to "Edit", edit_tenant_path(@apartment.tenants.first), class: "btn btn-warning" %>
                    <%= link_to "Issue Poolkey", "#", class: "btn btn-primary", data: { confirm: "This feature is in progress." } %>
                    <%= link_to "Issue Storage", "#", class: "btn btn-primary", data: { confirm: "This feature is in progress." } %>
                    <%= link_to "Evict", lease_path(@apartment.leases.ids), method: :delete, data: { confirm: "Are you really that heartless?" }, class: "btn btn-danger" %>
                    
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#payRent">
                      Pay Rent
                    </button>
                    
                    <!-- Modal -->
                    <div class="modal fade" id="payRent" tabindex="-1" role="dialog" aria-labelledby="Pay Rent">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">Pay Rent</h4>
                          </div>
                          <%= form_tag(new_rent_lease_path(@apartment.leases.first), method: :put) %>
                            <div class="modal-body">
                              <%= text_field_tag :new_rent, nil, class: "form-control" %>
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                              <input type="submit" name="commit" value="Submit" class="btn btn-primary" />
                            </div>
                        </div>
                      </div>
                    </div>
                <% else %>
                    <%= link_to "New Lease", new_lease_path, class: "btn btn-success" %>
                <% end %>
            </p>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MockingbirdManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style>
    .chriswidth {
      min-width: 210px;
    }
    .well {
      background-color: #fafafa;
    }
  </style>
</head>
<body>
    
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-brand"><%= link_to "MockingbirdManager", root_path %></div>
      <% if user_signed_in? %>
        <div class="nav navbar-nav navbar-right">
          <%= link_to "New Lease", new_lease_path, class: "btn btn-success navbar-btn" %>
          <%= link_to "New Application", new_tenant_path, class: "btn btn-info navbar-btn" %>
          <%= link_to "Sign Out", destroy_user_session_path, class: "btn btn-default navbar-btn", method: :delete %>
          <%= link_to "Edit Account", edit_user_registration_path, class: "btn btn-default navbar-btn" %>
        </div>
      <% else %>
        <div class="nav navbar-nav navbar-right">
          <%= form_for(:user, :url => session_path(:user)) do |f| %>
            <%= f.label :email %>
            <%= f.email_field :email, autofocus: true %>
            <%= f.label :password %>
            <%= f.password_field :password, autocomplete: "off" %>
            <%= f.submit "Log in", class: "btn btn-default navbar-btn" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </nav>
  
  
  <div class="container">
    <% if ! notice.nil? || ! alert.nil? %>
      <h3 class="notice text-danger text-center"><%= notice %><%= alert %></h3>
    <% end %>
      <%= yield %>
  </div>
  <br />
</body>
</html>

app/views/leases/_form.html.erb
<%= form_for @lease do |f| %>

  <div class="form-group">
    <%= f.label :tenant_id %>
    <br />
    <%= f.collection_select(:tenant_id, Tenant.all.select { |t| t.leases.count == 0 }, :id, :full_name, { prompt: true }, class: "form-control") %>
  </div>
  
  <div class="form-group">
    <%= f.label :apartment_id %>
    <br />
    <%= f.collection_select(:apartment_id, Apartment.all.select { |a| a.leases.count == 0 }, :id, :unit_name, { prompt: true }, class: "form-control") %>
  </div>
  
  <div class="form-group">
    <%= f.label :start_date %>
    <br />
    <%= f.text_field :start_date, class: "datepicker form-control" %>
    <script type="text/javascript">
      $(document).ready(function(){
        $('.datepicker').datepicker({
          format: 'yyyy-mm-dd'
        });
      });
    </script>
  </div>
  
  <div class="form-group">
    <%= f.label :end_date %>
    <br />
    <%= f.text_field :end_date, class: "datepicker form-control" %>
    <script type="text/javascript">
      $(document).ready(function(){
        $('.datepicker').datepicker({
          format: 'yyyy-mm-dd'
        });
      });
    </script>
  </div>
  
  <div class="form-group">
    <%= f.label :monthly_rent %>
    <br />
    <%= f.text_field :monthly_rent, class: 'form-control' %>
  </div>
  
  <div class="text-center"><%= f.submit "Submit", class: "btn btn-danger"%></div>
<% end %>

app/views/leases/edit.html.erb
<h1>edit</h1>

app/views/leases/index.html.erb
<h1>Leases</h1>

app/views/leases/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>New Lease</h1>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/leases/show.html.erb
<h1>Show</h1>

app/views/tenants/_form.html.erb
<%= form_for @tenant do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :dob %>
    <br />
    <%= f.text_field :dob, class: "datepicker form-control" %>
    <script type="text/javascript">
      $(document).ready(function(){
        $('.datepicker').datepicker({
          format: 'yyyy-mm-dd'
        });
      });
    </script>
  </div>
  <div class="form-group">
    <%= f.label :notes %>
    <br />
    <%= f.text_area :notes, class: 'form-control' %>
  </div>
  <div class="text-center"><%= f.submit "Submit", class: "btn btn-danger"%></div>
<% end %>

app/views/tenants/edit.html.erb
<h1>Edit Details for <%= @tenant.last_name %>, <%= @tenant.first_name %></h1>

<%= render 'form' %>

app/views/tenants/index.html.erb
<% @tenants.each do |t| %>
    <p>
        <%= link_to "#{t.last_name}, #{t.first_name}", tenant_path(t) %>
    </p>
<% end %>

app/views/tenants/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>New Tenant</h1>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/tenants/show.html.erb
<h1><%= @tenant.last_name %>, <%= @tenant.first_name %></h1>
<p>DOB: <%= @tenant.dob %></p>
<p>Notes: <%= @tenant.notes %></p>
<p><%= link_to "Edit", edit_tenant_path(@tenant) %></p>